my_site/blog/urls.py
from django.urls import path 
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name="post_list"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name="post_search"),
    
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'posts' : PostSitemap,}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(('blog.urls'), namespace="blog")),
    path('sitemap.xml', sitemap, {'sitemaps' : sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

my_site/blog/models.py
import email
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


class Post(models.Model):
    tags = TaggableManager()
    STATUS_CHOICES = (
        ('draft', 'Черновик'),
        ('published', 'Опубликовано')
    )
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    slug = models.SlugField(max_length=250, unique_for_date='publish', verbose_name="СЛАГ")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name="Автор")
    body = models.TextField(verbose_name="Текст")

    publish = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name="Статус")
    
    objects = models.Manager() # Обычные или все статьи
    published = PublishManager()  # Только опубликованные статьи

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day,
                                                        self.slug])

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title

    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name="пост")
    name = models.CharField(max_length=80, verbose_name="Имя")
    email = models.EmailField()
    body = models.TextField(verbose_name="Комментарий")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Создано")
    updated = models.DateTimeField(auto_now=True, verbose_name="Обновлено")
    active = models.BooleanField(default=True, verbose_name="Активно")

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Комментирует {} статью {}'.format(self.name, self.post)



    

my_site/blog/forms.py
from django import forms 
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label="Имя")
    email = forms.EmailField()
    to = forms.EmailField(label="Кому")
    comments = forms.CharField(required=False, widget=forms.Textarea, label="Комментарий")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField(label="Запрос")

my_site/blog/views.py
from argparse import Action
from re import search
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag 
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # По 3 статиь на каждой странице
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если страниц больше, чем общее количество страниц, возвращаем последнюю
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page' : page, 'posts' : posts, 'tag' : tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                                            publish__month=month, publish__day=day)
    #Список активных комментариев для статьи.
    comments = post.comments.filter(active=True)
    new_comment = None 
    if request.method == 'POST':
        # пользователь пытается отправить комментарий
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока что не сохраняем
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к статье
            new_comment.post = post 
            # Сохраняем комментарий в базе данных
            new_comment.save()
    else:
        comment_form = CommentForm()
    

    #Формирование списка похожих статей
    post_tags_ids = post.tags.values_list('id', flat=True) 
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]




    return render(request,'blog/post/detail.html',
                                            {'post' : post,
                                            'comments' : comments,
                                            'new_comment' : new_comment,
                                            'comment_form' : comment_form,
                                            'similar_posts' : similar_posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3 
    template_name = 'blog/post/list.html'

# Поделиться статьей по email
def post_share(request, post_id):
    # Получение статьи по id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False 

    if request.method == 'POST':
        # Форма была отправлена на сохранение
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                                        post.get_absolute_url())
            subject = '{} ({}) рекомендует к прочтению "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Прочитать "{}" по ссылке {}\n\n{}\ комментирует: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'koltsun-nv@yandex.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None 
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)

    if form.is_valid():
        query = form.cleaned_data['query']
        search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
        search_query = SearchQuery(query)
        results = Post.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.3).order_by('-similarity')
    return render(request, 'blog/post/search.html', {'form' : form, 'query' : query, 'results' : results})

my_site/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    <div id="content">
        {% block content %} {% endblock %}
    </div>
    <div id="sidebar">
        <h2>Мой блог</h2>
        <p>Это мой блог.</p>
        <p>Я написал {% total_posts %} постов</p>
        <h3>
            Последние посты:
        </h3>
        {% show_latest_posts 3 %}

        <h3>Самые комментируемые посты:</h3>
        {% get_most_commented_posts as most_comments_posts %}
        <ul>
            {% for post in most_comments_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>

        <p><a href="{% url 'blog:post_feed' %}">Подписка на мои новости</a></p>
    </div>
    
</body>
</html>

my_site/blog/templates/blog/pagination.html
<div class="paginator"> 
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Назад</a>
        {% endif %}
        <span class="current">
            Страница {{ page.number }} из {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Вперед</a>
        {% endif %}
    </span>
</div>

my_site/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}


{% block title %}{{ post.title }}{% endblock %}

{%  block content %}
    <h1>{{ post.title }}</h1>
    <p class="tags">Теги: {{ post.tags.all|join:", " }}</p>
    <p class="date">
        Опубликован: {{ post.publish }} Кем: {{ post.author }}
        {{ post.body|markdown }}
    </p>
    <p>
        <a href="#">Поделиться этой статьей</a>
    </p>

    <div>
        <h2>Похожие статьи:</h2>
        <div>
            {% for similar_post in similar_posts %}
                <p>
                    <a href="{{ similar_post.get_absolute_url }}">{{ similar_post.title }}</a>
                </p>
            {% endfor %}
        </div>
    </div>


    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} комментариев {{ total_comments|pluralize }}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} - {{ comment.name }}
                {{ comment.created }}
            </p>
            <p>
                {{ comment.body|linebreaks }}
            </p>
        </div>
    {% empty %}
        <p>Ни одного комментария нет.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Ваш комментарий был успешно добален!</h2>
    {% else %}
        <h2>Добавить комментарий</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Отправить"></p>
        </form>
    {% endif %}

{% endblock %}

my_site/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

my_site/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} Мой блог {% endblock %}

{% block content %} 
    <div>
        <h1 class="my_blog">Мой Блог</h1>
        <p><a href="{% url 'blog:post_search' %}">Поиск</a></p>
    </div>
    
    
    {% if tag %}
        <h2>Все посты по тегу "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>

        <p class="tags">
            Теги:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        
        
        <p class="date">
            Опубликована: {{ post.publish }} Кем: {{ post.author }}
        </p>
        <p>
            {{ post.body|truncatewords:30|markdown }}
        </p>
    {% endfor %}

    {% include "blog/pagination.html" with page=posts %}
{% endblock %}

my_site/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Посты включающие  "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Найдено {{ total_results }} результат {{ total_results|pluralize }}
            {% endwith %}
        </h3>

        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            <p>{{ post.body|truncatewords:5 }}</p>
        {% empty %}
            <p>Нет результатов по вашему запросу</p>
        {% endfor %}

        <p><a href="{% url 'blog:post_search' %}">Искать снова</a></p>
    {% else %}
        <h1>Поиск постов</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Поиск">
        </form>
    {% endif %}

{% endblock %}

my_site/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Поделилиться статьей{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail успешно отправлен</h1>
        <p>{{ post.title }} было успешно отправлено: {{ form.cleaned_data.to }}</p>
    {% else %}
        <h1>Поделиться {{ post.title }} с помощью e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить">
        </form>
    {% endif %}
{% endblock %}